server:
  port: ${SERVER_PORT}

spring:
  application:
    name: DVFashion
  # Database
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  # OAuth2 Client Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: ${BACKEND_URL}/login/oauth2/code/{registrationId}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  # OpenAI Configuration
  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
  # Email Configuration
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # File upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
# Frontend URL for OAuth2 redirection
oauth2:
  redirect-uris:
    success: ${FRONTEND_URL:http://localhost:5173}/oauth2/redirect
    failure: ${FRONTEND_URL:http://localhost:5173}/oauth2/redirect?error=true

# Logging configuration
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG

# Base path for the API
web:
  base-path: /api/v1
  frontend-base-url: ${FRONTEND_URL}

# Security
jwt:
  signed-key: ${JWT_SIGNED_KEY}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  secret-key: ${JWT_SECRET_KEY}

# Cloudinary configuration
cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# Url for resetting password
app:
  reset-password-url: ${RESET_PASSWORD_URL}

# Recommendation service configuration
recommendation:
  service:
    url: ${RECOMMENDATION_SERVICE_URL}

# PayPal configuration
paypal:
  base-url: https://api-m.sandbox.paypal.com
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  mode: ${PAYPAL_MODE}
  success-url: http://localhost:8080/api/v1/payments/paypal/success
  cancel-url: http://localhost:8080/api/v1/payments/paypal/cancel

# GHN (Giao HÃ ng Nhanh) configuration
ghn:
  base-url: ${GHN_BASE_URL}
  token: ${GHN_TOKEN}
  shop-id: ${GHN_SHOP_ID}
  shop-name: ${GHN_SHOP_NAME}

# Brevo (formerly Sendinblue) configuration
brevo:
  api-key: ${BREVO_API_KEY}
  sender-email: ${SENDER_EMAIL}
  sender-name: ${SENDER_NAME}
  brevo-base-url: ${BREVO_BASE_URL}